### ISSUE TITLE
Nether is broken with this mod

### ISSUE THREAD

**Issue by CritFlaw** [DoubleDoorDevelopment/Lumberjack#28]
Hours and hours of debugging, I've isolated [this](https://github.com/McJtyMods/TheOneProbe/issues/285) issue to your mod.

**Comment by Claycorp** [comment]
Uhh? Are you sure? This mod doesn't touch any rendering and only adds axes that does some connected destruction based off events.
What method did you use to find the issue? 

I currently have nothing to go off of other than TOP breaks in the nether the log has nothing, the video only shows it doesn't work.

**Comment by Claycorp** [comment]
https://i.imgur.com/54Kb44d.png
TOP and Lumberjack seems to work fine.

**Comment by CritFlaw** [comment]
It's not TOP specifically. TOP just showed a symptom of the issue, and that issue report had all the information in one post. After hours of disabling mods and relaunching I didn't feel like writing a whole new post.

**Comment by CritFlaw** [comment]
It's still happening without Lumberjack on going to the nether again.... kill me.

**Comment by Claycorp** [comment]
I was going to say this mod doesn't touch the nether only. If you where to have issues it would have been everywhere.

If it only happens when going to the nether via portal and a reconnect fixes it that sounds like a player desync of some sort. Start looking at mods that modify teleportation and dimension based things.

I'm going to close this, Good luck tracking it down.
